name: Examples

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: Test examples
    runs-on: ${{ matrix.os }}
    env:
      RELEASE: false
    strategy:
      matrix:
        os: [ubuntu-latest]
        python_version: [3.9]

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: 'recursive'

    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python_version }}

    - name: Create virtualenv
      shell: bash
      run: |
        pip install virtualenv
        python -m virtualenv venv

    - name: Install dependencies
      shell: bash
      run: |
        pip install poetry
        source venv/bin/activate || source venv/Scripts/activate
        make build
  
    - name: Set up ActivityWatch
      uses: ActivityWatch/setup-action@master
      with:
        aw-server: "aw-server"
        aw-version: "v0.12.0b2"
        aw-testing: false
        fakedata: true

    - name: Run examples
      shell: bash
      run: |
        source venv/bin/activate || source venv/Scripts/activate
        pip install pandas  # needed for one of the examples
        make test-examples
